/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShareRouteImport } from './routes/share'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HighScoreRouteImport } from './routes/high-score'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueGameIdRouteImport } from './routes/queue.$gameId'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HighScoreRoute = HighScoreRouteImport.update({
  id: '/high-score',
  path: '/high-score',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueGameIdRoute = QueueGameIdRouteImport.update({
  id: '/queue/$gameId',
  path: '/queue/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/compare': typeof CompareRoute
  '/complete': typeof CompleteRoute
  '/discover': typeof DiscoverRoute
  '/family': typeof FamilyRoute
  '/favourites': typeof FavouritesRoute
  '/high-score': typeof HighScoreRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/rewards': typeof RewardsRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splash': typeof SplashRoute
  '/summary': typeof SummaryRoute
  '/support': typeof SupportRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/queue/$gameId': typeof QueueGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/compare': typeof CompareRoute
  '/complete': typeof CompleteRoute
  '/discover': typeof DiscoverRoute
  '/family': typeof FamilyRoute
  '/favourites': typeof FavouritesRoute
  '/high-score': typeof HighScoreRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/rewards': typeof RewardsRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splash': typeof SplashRoute
  '/summary': typeof SummaryRoute
  '/support': typeof SupportRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/queue/$gameId': typeof QueueGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/compare': typeof CompareRoute
  '/complete': typeof CompleteRoute
  '/discover': typeof DiscoverRoute
  '/family': typeof FamilyRoute
  '/favourites': typeof FavouritesRoute
  '/high-score': typeof HighScoreRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/rewards': typeof RewardsRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splash': typeof SplashRoute
  '/summary': typeof SummaryRoute
  '/support': typeof SupportRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/queue/$gameId': typeof QueueGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/compare'
    | '/complete'
    | '/discover'
    | '/family'
    | '/favourites'
    | '/high-score'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/otp'
    | '/rewards'
    | '/share'
    | '/signup'
    | '/sitemap.xml'
    | '/splash'
    | '/summary'
    | '/support'
    | '/game/$gameId'
    | '/queue/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/compare'
    | '/complete'
    | '/discover'
    | '/family'
    | '/favourites'
    | '/high-score'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/otp'
    | '/rewards'
    | '/share'
    | '/signup'
    | '/sitemap.xml'
    | '/splash'
    | '/summary'
    | '/support'
    | '/game/$gameId'
    | '/queue/$gameId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/compare'
    | '/complete'
    | '/discover'
    | '/family'
    | '/favourites'
    | '/high-score'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/otp'
    | '/rewards'
    | '/share'
    | '/signup'
    | '/sitemap.xml'
    | '/splash'
    | '/summary'
    | '/support'
    | '/game/$gameId'
    | '/queue/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CompareRoute: typeof CompareRoute
  CompleteRoute: typeof CompleteRoute
  DiscoverRoute: typeof DiscoverRoute
  FamilyRoute: typeof FamilyRoute
  FavouritesRoute: typeof FavouritesRoute
  HighScoreRoute: typeof HighScoreRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  RewardsRoute: typeof RewardsRoute
  ShareRoute: typeof ShareRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SplashRoute: typeof SplashRoute
  SummaryRoute: typeof SummaryRoute
  SupportRoute: typeof SupportRoute
  GameGameIdRoute: typeof GameGameIdRoute
  QueueGameIdRoute: typeof QueueGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-score': {
      id: '/high-score'
      path: '/high-score'
      fullPath: '/high-score'
      preLoaderRoute: typeof HighScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$gameId': {
      id: '/queue/$gameId'
      path: '/queue/$gameId'
      fullPath: '/queue/$gameId'
      preLoaderRoute: typeof QueueGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CompareRoute: CompareRoute,
  CompleteRoute: CompleteRoute,
  DiscoverRoute: DiscoverRoute,
  FamilyRoute: FamilyRoute,
  FavouritesRoute: FavouritesRoute,
  HighScoreRoute: HighScoreRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  RewardsRoute: RewardsRoute,
  ShareRoute: ShareRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SplashRoute: SplashRoute,
  SummaryRoute: SummaryRoute,
  SupportRoute: SupportRoute,
  GameGameIdRoute: GameGameIdRoute,
  QueueGameIdRoute: QueueGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
